# Generated by Django 6.0.7 on 2026-07-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='식별자')),
                ('emoji', models.CharField(max_length=8, verbose_name='이모지')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('description', models.CharField(max_length=200, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '코스',
                'verbose_name_plural': '코스',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='식별자')),
                ('emoji', models.CharField(max_length=8, verbose_name='이모지')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('goal', models.CharField(max_length=200, verbose_name='학습 목표')),
                ('minutes', models.IntegerField(default=5, verbose_name='예상 소요 시간(분)')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='smartstep.course', verbose_name='코스')),
            ],
            options={
                'verbose_name': '챕터',
                'verbose_name_plural': '챕터',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='세션 키')),
                ('last_step', models.IntegerField(default=0, verbose_name='마지막으로 본 단계')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='smartstep.chapter', verbose_name='챕터')),
            ],
            options={
                'verbose_name': '진도',
                'verbose_name_plural': '진도',
                'ordering': ['-updated_at'],
                'unique_together': {('session_key', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='단계 순서')),
                ('instruction', models.CharField(max_length=200, verbose_name='안내 문구')),
                ('html', models.TextField(verbose_name='폰 화면 마크업')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='smartstep.chapter', verbose_name='챕터')),
            ],
            options={
                'verbose_name': '스텝',
                'verbose_name_plural': '스텝',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
